#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# cuss-kernel
# Copyright (C) 2026 SnapKitty Collective
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

"""gen_demos.py - embed programs/*.cuss as C string literals for the kernel.

Usage: python3 tools/gen_demos.py programs/*.cuss > kernel/demos_gen.h
Single source of truth: the shell's `demo` command serves these.
"""
import sys
import os


def c_escape(data: bytes) -> str:
    out = []
    for b in data:
        if b == 0x0A:
            out.append("\\n")
        elif b == 0x5C:
            out.append("\\\\")
        elif b == 0x22:
            out.append('\\"')
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\x%02x" % b)
    return "".join(out)


def main():
    print("/* demos_gen.h - AUTO-GENERATED by tools/gen_demos.py. Do not edit. */")
    names = []
    for path in sys.argv[1:]:
        name = os.path.splitext(os.path.basename(path))[0]
        ident = "".join(c if c.isalnum() else "_" for c in name)
        names.append((name, ident))
        with open(path, "rb") as f:
            data = f.read()
        print(f'static const char demo_{ident}_src[] = "{c_escape(data)}";')
    print("typedef struct { const char *name; const char *src; } demo_t;")
    print("static const demo_t demos[] = {")
    for name, ident in names:
        print(f'    {{ "{name}", demo_{ident}_src }},')
    print("};")
    print(f"#define NDEMOS {len(names)}")


if __name__ == "__main__":
    main()
